name: sample
on: [push]
jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8.5
      - name: Install dependencies
        run: |
          python -m pip install pylint pytest
      - name: Lint
        run: pylint add.py
      - name: Test
        run: python -m pytest test.py
